config/routes.rb
SampleApp::Application.routes.draw do
  resources :user_profiles
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root :to => 'static_pages#home'
  
  match '/help', to:'static_pages#help'
  match '/about', to:'static_pages#about'
  match '/contact', to:'static_pages#contact'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'

  
  
    

end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
  attr_accessible :profile_active, :profile_admin, :profile_code, :profile_name
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  before_filter :signed_in_user, :only => [:edit, :index, :show, :update, :destroy,:new, :create]
  before_filter :admin_user,   :only => [:destroy]

  # GET /user_profiles
  # GET /user_profiles.json
  def index
    @user_profiles = UserProfile.paginate(page: params[:page])
  end

  # GET /user_profiles/1
  # GET /user_profiles/1.json
  def show
    @user_profile = UserProfile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_profile }
    end
  end

  # GET /user_profiles/new
  # GET /user_profiles/new.json
  def new
    @user_profile = UserProfile.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_profile }
    end
  end

  # GET /user_profiles/1/edit
  def edit
    @user_profile = UserProfile.find(params[:id])
  end

  # POST /user_profiles
  # POST /user_profiles.json
  def create
    @user_profile = UserProfile.new(params[:user_profile])

    respond_to do |format|
      if @user_profile.save
        format.html { redirect_to @user_profile, notice: 'User profile was successfully created.' }
        format.json { render json: @user_profile, status: :created, location: @user_profile }
      else
        format.html { render action: "new" }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_profiles/1
  # PUT /user_profiles/1.json
  def update
    @user_profile = UserProfile.find(params[:id])

    respond_to do |format|
      if @user_profile.update_attributes(params[:user_profile])
        format.html { redirect_to @user_profile, notice: 'User profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_profiles/1
  # DELETE /user_profiles/1.json
  def destroy
    @user_profile = UserProfile.find(params[:id])
    @user_profile.destroy

    respond_to do |format|
      format.html { redirect_to user_profiles_url }
      format.json { head :no_content }
    end
  end

   private
     
     def signed_in_user
      unless signed_in?
        store_location
        #redirect_to signin_url, notice: "Please sign in."
        flash[:notice] = "Please sign in."
        redirect_to signin_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
    
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end

     private
     
     def signed_in_user
      unless signed_in?
        store_location
        #redirect_to signin_url, notice: "Please sign in."
        flash[:notice] = "Please sign in."
        redirect_to signin_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
    
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end


end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/user_profiles/_form.html.erb
<%= form_for(@user_profile) do |f| %>
  <% if @user_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_profile.errors.count, "error") %> prohibited this user_profile from being saved:</h2>

      <ul>
      <% @user_profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :profile_code %><br />
    <%= f.text_field :profile_code %>
  </div>
  <div class="field">
    <%= f.label :profile_name %><br />
    <%= f.text_field :profile_name %>
  </div>
  <div class="field">
    <%= f.label :profile_active %><br />
    <%= f.check_box :profile_active %>
  </div>
  <div class="field">
    <%= f.label :profile_admin %><br />
    <%= f.check_box :profile_admin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_profiles/edit.html.erb
<% provide(:title, 'Edit User Profile') %>
<h1>Editing User Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_profile %> |
<%= link_to 'Back', user_profiles_path %>

app/views/user_profiles/index.html.erb
<% provide(:title, "User Profiles") %> 
<h1>User Profiles</h1>

<%= will_paginate %>

<table class="table">
  <tr>
    <th>Profile code</th>
    <th>Profile name</th>
    <th>Profile active</th>
    <th>Profile admin</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_profiles.each do |user_profile| %>
  <tr>
    <td><%= user_profile.profile_code %></td>
    <td><%= user_profile.profile_name %></td>
    <td><%= user_profile.profile_active %></td>
    <td><%= user_profile.profile_admin %></td>
    <td><%= link_to 'Show', user_profile %></td>
    <td><%= link_to 'Edit', edit_user_profile_path(user_profile) %></td>
    <td><%= link_to 'Destroy', user_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User profile', new_user_profile_path %>
<%= will_paginate %>

app/views/user_profiles/new.html.erb
<% provide(:title, 'Create User Profile') %>
<h1>New User Profile</h1>

<div class="row">
  <div class="span6 offset3">
	<%= render 'form'%>
   </div>
</div> 	

<%= link_to 'Back', user_profiles_path %>

app/views/user_profiles/show.html.erb
<% provide(:title, 'View User Profile') %>
<p id="notice"><%= notice %></p>

<p>
  <b>Profile code:</b>
  <%= @user_profile.profile_code %>
</p>

<p>
  <b>Profile name:</b>
  <%= @user_profile.profile_name %>
</p>

<p>
  <b>Profile active:</b>
  <%= @user_profile.profile_active %>
</p>

<p>
  <b>Profile admin:</b>
  <%= @user_profile.profile_admin %>
</p>


<%= link_to 'Edit', edit_user_profile_path(@user_profile) %> |
<%= link_to 'Back', user_profiles_path %>