config/routes.rb
SampleApp::Application.routes.draw do
  resources :user_profiles
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root :to => 'static_pages#home'
  
  match '/help', to:'static_pages#help'
  match '/about', to:'static_pages#about'
  match '/contact', to:'static_pages#contact'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'

  
  
    

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<center>12112012200000</center>
	<small>
		<%= link_to image_tag("tsslogo.jpg", alt: "TrustScan"), 'http://www.trustscan-solutions.com' %>
	</small>
	<nav>
  		<ul class="nav pull-right">
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
          <li><%= link_to "News", '#' %></li>
        </ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Trustscan Solutions S.L.", root_path, id: "logo" %>
      <nav> 
        <ul class="nav pull-right">


          
          <% if signed_in? %> 
           <% if current_user.admin?  %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Admin <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Users", users_path %></li>
                <li><%= link_to "Create User", signup_path %></li>
                <li class="divider"></li>
                <li><%= link_to "User Profiles", user_profiles_path %></li>
                <li><%= link_to 'New User profile', new_user_profile_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Case Model", '#' %></li>
                <li><%= link_to 'New Case model', '#' %></li>
                <li class="divider"></li>
                <li><%= link_to "Document Model", '#' %></li>
                <li><%= link_to 'New Document model', '#' %></li>
              </ul>
            </li>
          <% end %>
            <li><%= link_to 'My Cases', '#' %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user.name %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Help", help_path %></li>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>

  </body>

</html>